---
- name: Setup NGINX Web Server
  hosts: nginx-web-server
  become: yes
  tasks:
  - name: Add CentOS EPEL Release
    yum:
      name: epel-release
      state: present
  - name: Install NGINX
    yum:
      name: nginx
      state: present
  - name: Install PHP
    yum:
      name: php
      state: present
  - name: Install PHP-FPM
    yum:
      name: php-fpm
      state: present
---
  - name: Configure PHP-FPM Listening port
    copy:
      src: config/php-nginx/www.conf
      dest: /etc/php-fpm.d/www.conf
      owner: root
      group: root
  - name: Configure NGINX Listening port
    copy:
      src: config/php-nginx/default.conf
      dest: /etc/nginx/conf.d/default.conf
      owner: root
      group: root
  - name: Create base html folder for NGINX
    file:
      path: /opt/html
      state: directory
      mode: '0755'
      owner: nginx
      group: nginx
  - name: Copy index.php files inside vm
    copy:
      src: config/php-nginx/index.php
      dest: /opt/html/index.php
      owner: nginx
      group: nginx
  - name: ensure nginx is restarted
    service:
      name: nginx
      state: restarted
  - name: ensure php-fpm is restarted
    service:
      name: php-fpm
      state: restarted
  - name: Open port 40080 for nginx access
    firewalld:
      port: 40080/tcp
      permanent: true
      state: enabled
  - name: Restart the firewalld service to load in the firewall changes
    service:
      name: firewalld
      state: restarted
